language: node_js
node_js:
  - '14'
sudo: required
services:
  - docker

before_install:
  - docker build -t patrickliu022/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true patrickliu022/docker-react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-664029833137" 
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY